function Hd = bandpass_func(Fstop1, Fpass1, Fpass2, Fstop2)
%BANDPASS_FUNCN100 Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 7.14 and the Signal Processing Toolbox 6.17.
%
% Generated on: 20-Oct-2016 10:25:56
%

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 32;  % New sampling Frequency (1/(8/256)). Fs=256 Hz, fhop=8 (32/4)
%where 32 is the number of points of the window size. 4 is because the
%overlap is 75%

N      = 100;     % Order
Wstop1 = 1;       % First Stopband Weight
Wpass  = 1;       % Passband Weight
Wstop2 = 1;       % Second Stopband Weight
dens   = 20;      % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fstop1 Fpass1 Fpass2 Fstop2 Fs/2]/(Fs/2), [0 0 1 1 0 ...
           0], [Wstop1 Wpass Wstop2], {dens});
Hd = dfilt.dffir(b);

% [EOF]
