function Hd = filter_lowpass_fir(fc, fs)
%FILTER_LOWPASS_FIR Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the Signal Processing Toolbox 7.0.
% Generated on: 24-Aug-2017 14:24:25

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = fs;  % Sampling Frequency

Fpass = fc * 0.90;       % Passband Frequency
Fstop = fc * 1.10;       % Stopband Frequency
Apass  = 1;              % Passband Ripple (dB)
Astop = 40;             % Stopband Attenuation (dB)
dens  = 20;              % Density Factor

% Compute deviations
Dpass = (10^(Apass/20)-1)/(10^(Apass/20)+1);
Dstop = 10^(-Astop/20);

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
